apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend-3
  template:
    metadata:
      labels:
        app: flask-backend-3
    spec:
      containers:
      - name: flask-backend
        image: santiagobv/mlip_backend:1.0.0
        ports:
        - containerPort: 5001